### PR TITLE
Fix #28

### LINKED ISSUE #28: `ghostupmin_last`: Why does it suddenly become extra large?
A couple of days after this happened: https://ukadon.shillest.net/@steve02081504/110377447233979121
I found that my ghost's `ghostupmin_last` had somehow become unbelievably huge again (thank goodness I didn't push this change to the stable mirror!)
image
I thought it must be something wrong, but I looked for where `ghostupmin_last` was updated and I found that it was only updated on `unload`
What I can think of is that perhaps there is some `unload` call where shiori is not getting the current time correctly and is returning confusing values
Maybe when ssp automatically exits when the computer is shut down?
Or maybe some other time?
I'm not sure, but this issue definitely needs to be fixed.

### PR DESCRIPTION
**Pull request by nikolat**
set `ghostupmin` to 0 when `ghostbootmin` is undefined
for #28

### CODE REVIEW

**Comment by steve02081504** [comment]
图片
It looks like yaya already treats variables as `0` when they are undefined, so I'm not sure if this fix will work
For me, I think I'll make these changes to my ghost and wait a few days to see if it works.

**Review by steve02081504 — COMMENTED** [review]
ohhhhhh I see what you mean!
Sorry I'm having a viral cold today so my brain is always slow(ノω<)
Looking good for me!

**Comment by steve02081504** [comment]
I just noticed that all global variables are removed on `LOADVAR` and the contents of the archive file are then loaded, maybe this means that `ghostbootmin` goes back to undefined every time the archive file saved on normal exit is loaded?
Maybe we should provide some functionality in shiori to allow certain functions to be run each time `LOADVAR` is loaded, or allow the dic file to add certain variables to the `LOADVAR` whitelist to keep them alive
I'm not sure, all I have is a headache and aching limbs

**Comment by steve02081504** [comment]
Oh sorry I seem to have misread it
Maybe I'm more suited to sleeping than reading code at the momenti😂🤦‍♂️

**Comment by steve02081504** [comment]
**Sorry to interrupt** but this is another possible fix✨ (maybe you'd like to accept it)
The existing fix is fine, the two approaches are just different design ideas
https://github.com/Taromati2/ghost/commit/f457d45121876824c8f9b896ec144b1cf8e70d9c
Now I can go to bed in peace.💤

**Review by ponapalt — APPROVED** [review]

**Pull request merged**
